/*
 * BVNK API Endpoints
 * The BVNK API is designed to facilitate seamless and secure transactions including payments, channels, anddigital wallet transactions.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.ValidationErrorDto;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ClientValidationErrorDto
 */
public class ClientValidationErrorDtoTest {
    private final ClientValidationErrorDto model = new ClientValidationErrorDto();

    /**
     * Model tests for ClientValidationErrorDto
     */
    @Test
    public void testClientValidationErrorDto() {
        // TODO: test ClientValidationErrorDto
    }

    /**
     * Test the property 'errorList'
     */
    @Test
    public void errorListTest() {
        // TODO: test errorList
    }

}
