/*
 * BVNK API Endpoints
 * The BVNK API is designed to facilitate seamless and secure transactions including payments, channels, anddigital wallet transactions.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CurrencyFiat
 */
public class CurrencyFiatTest {
    private final CurrencyFiat model = new CurrencyFiat();

    /**
     * Model tests for CurrencyFiat
     */
    @Test
    public void testCurrencyFiat() {
        // TODO: test CurrencyFiat
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'depositFee'
     */
    @Test
    public void depositFeeTest() {
        // TODO: test depositFee
    }

    /**
     * Test the property 'fiat'
     */
    @Test
    public void fiatTest() {
        // TODO: test fiat
    }

    /**
     * Test the property 'icon'
     */
    @Test
    public void iconTest() {
        // TODO: test icon
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'options'
     */
    @Test
    public void optionsTest() {
        // TODO: test options
    }

    /**
     * Test the property 'pricePrecision'
     */
    @Test
    public void pricePrecisionTest() {
        // TODO: test pricePrecision
    }

    /**
     * Test the property 'protocols'
     */
    @Test
    public void protocolsTest() {
        // TODO: test protocols
    }

    /**
     * Test the property 'quantityPrecision'
     */
    @Test
    public void quantityPrecisionTest() {
        // TODO: test quantityPrecision
    }

    /**
     * Test the property 'supportsDeposits'
     */
    @Test
    public void supportsDepositsTest() {
        // TODO: test supportsDeposits
    }

    /**
     * Test the property 'supportsWithdrawals'
     */
    @Test
    public void supportsWithdrawalsTest() {
        // TODO: test supportsWithdrawals
    }

    /**
     * Test the property 'withdrawalFee'
     */
    @Test
    public void withdrawalFeeTest() {
        // TODO: test withdrawalFee
    }

    /**
     * Test the property 'withdrawalParameters'
     */
    @Test
    public void withdrawalParametersTest() {
        // TODO: test withdrawalParameters
    }

}
