/*
 * BVNK API Endpoints
 * The BVNK API is designed to facilitate seamless and secure transactions including payments, channels, anddigital wallet transactions.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.ExchangeRateDto;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for GatewayTransactionDto
 */
public class GatewayTransactionDtoTest {
    private final GatewayTransactionDto model = new GatewayTransactionDto();

    /**
     * Model tests for GatewayTransactionDto
     */
    @Test
    public void testGatewayTransactionDto() {
        // TODO: test GatewayTransactionDto
    }

    /**
     * Test the property 'dateCreated'
     */
    @Test
    public void dateCreatedTest() {
        // TODO: test dateCreated
    }

    /**
     * Test the property 'dateConfirmed'
     */
    @Test
    public void dateConfirmedTest() {
        // TODO: test dateConfirmed
    }

    /**
     * Test the property 'hash'
     */
    @Test
    public void hashTest() {
        // TODO: test hash
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'risk'
     */
    @Test
    public void riskTest() {
        // TODO: test risk
    }

    /**
     * Test the property 'networkFeeCurrency'
     */
    @Test
    public void networkFeeCurrencyTest() {
        // TODO: test networkFeeCurrency
    }

    /**
     * Test the property 'networkFeeAmount'
     */
    @Test
    public void networkFeeAmountTest() {
        // TODO: test networkFeeAmount
    }

    /**
     * Test the property 'sources'
     */
    @Test
    public void sourcesTest() {
        // TODO: test sources
    }

    /**
     * Test the property 'displayRate'
     */
    @Test
    public void displayRateTest() {
        // TODO: test displayRate
    }

    /**
     * Test the property 'exchangeRate'
     */
    @Test
    public void exchangeRateTest() {
        // TODO: test exchangeRate
    }

}
