/*
 * BVNK API Endpoints
 * The BVNK API is designed to facilitate seamless and secure transactions including payments, channels, anddigital wallet transactions.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for MerchantChannelRequest
 */
public class MerchantChannelRequestTest {
    private final MerchantChannelRequest model = new MerchantChannelRequest();

    /**
     * Model tests for MerchantChannelRequest
     */
    @Test
    public void testMerchantChannelRequest() {
        // TODO: test MerchantChannelRequest
    }

    /**
     * Test the property 'merchantId'
     */
    @Test
    public void merchantIdTest() {
        // TODO: test merchantId
    }

    /**
     * Test the property 'payCurrency'
     */
    @Test
    public void payCurrencyTest() {
        // TODO: test payCurrency
    }

    /**
     * Test the property 'displayCurrency'
     */
    @Test
    public void displayCurrencyTest() {
        // TODO: test displayCurrency
    }

    /**
     * Test the property 'reference'
     */
    @Test
    public void referenceTest() {
        // TODO: test reference
    }

}
