/*
 * BVNK API Endpoints
 * The BVNK API is designed to facilitate seamless and secure transactions including payments, channels, anddigital wallet transactions.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import org.openapitools.client.model.DirectionDto;
import org.openapitools.client.model.PayInDetailDto;
import org.openapitools.client.model.PayOutDetailDto;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PayRequestDto
 */
public class PayRequestDtoTest {
    private final PayRequestDto model = new PayRequestDto();

    /**
     * Model tests for PayRequestDto
     */
    @Test
    public void testPayRequestDto() {
        // TODO: test PayRequestDto
    }

    /**
     * Test the property 'merchantId'
     */
    @Test
    public void merchantIdTest() {
        // TODO: test merchantId
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'expiryMinutes'
     */
    @Test
    public void expiryMinutesTest() {
        // TODO: test expiryMinutes
    }

    /**
     * Test the property 'currency'
     */
    @Test
    public void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'returnUrl'
     */
    @Test
    public void returnUrlTest() {
        // TODO: test returnUrl
    }

    /**
     * Test the property 'reference'
     */
    @Test
    public void referenceTest() {
        // TODO: test reference
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'payInDetails'
     */
    @Test
    public void payInDetailsTest() {
        // TODO: test payInDetails
    }

    /**
     * Test the property 'payOutDetails'
     */
    @Test
    public void payOutDetailsTest() {
        // TODO: test payOutDetails
    }

}
