/*
 * BVNK API Endpoints
 * The BVNK API is designed to facilitate seamless and secure transactions including payments, channels, anddigital wallet transactions.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.CryptoAddressDto;
import org.openapitools.client.model.DirectionDto;
import org.openapitools.client.model.ExchangeRateDto;
import org.openapitools.client.model.GatewayTransactionDto;
import org.openapitools.client.model.PayAmountsDto;
import org.openapitools.client.model.PaymentStatusDto;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for SummaryPaymentDto
 */
public class SummaryPaymentDtoTest {
    private final SummaryPaymentDto model = new SummaryPaymentDto();

    /**
     * Model tests for SummaryPaymentDto
     */
    @Test
    public void testSummaryPaymentDto() {
        // TODO: test SummaryPaymentDto
    }

    /**
     * Test the property 'uuid'
     */
    @Test
    public void uuidTest() {
        // TODO: test uuid
    }

    /**
     * Test the property 'merchantDisplayName'
     */
    @Test
    public void merchantDisplayNameTest() {
        // TODO: test merchantDisplayName
    }

    /**
     * Test the property 'merchantId'
     */
    @Test
    public void merchantIdTest() {
        // TODO: test merchantId
    }

    /**
     * Test the property 'dateCreated'
     */
    @Test
    public void dateCreatedTest() {
        // TODO: test dateCreated
    }

    /**
     * Test the property 'expiryDate'
     */
    @Test
    public void expiryDateTest() {
        // TODO: test expiryDate
    }

    /**
     * Test the property 'quoteExpiryDate'
     */
    @Test
    public void quoteExpiryDateTest() {
        // TODO: test quoteExpiryDate
    }

    /**
     * Test the property 'acceptanceExpiryDate'
     */
    @Test
    public void acceptanceExpiryDateTest() {
        // TODO: test acceptanceExpiryDate
    }

    /**
     * Test the property 'quoteStatus'
     */
    @Test
    public void quoteStatusTest() {
        // TODO: test quoteStatus
    }

    /**
     * Test the property 'reference'
     */
    @Test
    public void referenceTest() {
        // TODO: test reference
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'subType'
     */
    @Test
    public void subTypeTest() {
        // TODO: test subType
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'displayCurrency'
     */
    @Test
    public void displayCurrencyTest() {
        // TODO: test displayCurrency
    }

    /**
     * Test the property 'walletCurrency'
     */
    @Test
    public void walletCurrencyTest() {
        // TODO: test walletCurrency
    }

    /**
     * Test the property 'paidCurrency'
     */
    @Test
    public void paidCurrencyTest() {
        // TODO: test paidCurrency
    }

    /**
     * Test the property 'feeCurrency'
     */
    @Test
    public void feeCurrencyTest() {
        // TODO: test feeCurrency
    }

    /**
     * Test the property 'displayRate'
     */
    @Test
    public void displayRateTest() {
        // TODO: test displayRate
    }

    /**
     * Test the property 'exchangeRate'
     */
    @Test
    public void exchangeRateTest() {
        // TODO: test exchangeRate
    }

    /**
     * Test the property 'address'
     */
    @Test
    public void addressTest() {
        // TODO: test address
    }

    /**
     * Test the property 'returnUrl'
     */
    @Test
    public void returnUrlTest() {
        // TODO: test returnUrl
    }

    /**
     * Test the property 'redirectUrl'
     */
    @Test
    public void redirectUrlTest() {
        // TODO: test redirectUrl
    }

    /**
     * Test the property 'transactions'
     */
    @Test
    public void transactionsTest() {
        // TODO: test transactions
    }

    /**
     * Test the property 'refund'
     */
    @Test
    public void refundTest() {
        // TODO: test refund
    }

    /**
     * Test the property 'refunds'
     */
    @Test
    public void refundsTest() {
        // TODO: test refunds
    }

}
