/*
 * BVNK API Endpoints
 * The BVNK API is designed to facilitate seamless and secure transactions including payments, channels, anddigital wallet transactions.
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.ValidationErrorDto;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * List of validation errors
 */
@Schema(description = "List of validation errors")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-07-05T20:47:27.517449+02:00[Africa/Johannesburg]")

public class ClientValidationErrorDto {
  @SerializedName("errorList")
  private List<ValidationErrorDto> errorList = null;

  public ClientValidationErrorDto errorList(List<ValidationErrorDto> errorList) {
    this.errorList = errorList;
    return this;
  }

  public ClientValidationErrorDto addErrorListItem(ValidationErrorDto errorListItem) {
    if (this.errorList == null) {
      this.errorList = new ArrayList<ValidationErrorDto>();
    }
    this.errorList.add(errorListItem);
    return this;
  }

   /**
   * Get errorList
   * @return errorList
  **/
  @Schema(description = "")
  public List<ValidationErrorDto> getErrorList() {
    return errorList;
  }

  public void setErrorList(List<ValidationErrorDto> errorList) {
    this.errorList = errorList;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClientValidationErrorDto clientValidationErrorDto = (ClientValidationErrorDto) o;
    return Objects.equals(this.errorList, clientValidationErrorDto.errorList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(errorList);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClientValidationErrorDto {\n");
    
    sb.append("    errorList: ").append(toIndentedString(errorList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
