/*
 * BVNK API Endpoints
 * The BVNK API is designed to facilitate seamless and secure transactions including payments, channels, anddigital wallet transactions.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.Balance;
import org.openapitools.client.model.ServerErrorDto;
import org.openapitools.client.model.TransactionReport;
import org.openapitools.client.model.Wallet;
import org.openapitools.client.model.WalletRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for WalletsApi
 */
@Disabled
public class WalletsApiTest {

    private final WalletsApi api = new WalletsApi();

    /**
     * Transactions Report
     *
     * Report all transactions from wallet in specified format. Report will be generated and sent to main account email in the specified format
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void transactionReportTest() throws ApiException {
        Long walletId = null;
        String fromDate = null;
        String toDate = null;
        String format = null;
        String transactionType = null;
        List<TransactionReport> response = api.transactionReport(walletId, fromDate, toDate, format, transactionType);
        // TODO: test validations
    }

    /**
     * List Wallet Balances
     *
     * Retrieves the balances of your wallets on platform.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void walletBalanceListTest() throws ApiException {
        String date = null;
        List<Balance> response = api.walletBalanceList(date);
        // TODO: test validations
    }

    /**
     * Create Wallet
     *
     * Creates a wallet on the BVNK platform.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void walletCreateTest() throws ApiException {
        WalletRequest walletRequest = null;
        Wallet response = api.walletCreate(walletRequest);
        // TODO: test validations
    }

    /**
     * List Wallets
     *
     * Retrieves a list of wallets on your account.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void walletListTest() throws ApiException {
        Integer offset = null;
        Integer max = null;
        List<Wallet> response = api.walletList(offset, max);
        // TODO: test validations
    }

    /**
     * Get Wallet
     *
     * Retrieves a specific wallet.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void walletRGetTest() throws ApiException {
        Long id = null;
        Wallet response = api.walletRGet(id);
        // TODO: test validations
    }

}
